CREATE EXTERNAL TABLE IF NOT EXISTS AIRPORTS
	(iata STRING,
	airport STRING,
	city STRING,
	state STRING,
	country STRING,
	lat STRING,
	lon STRING)
ROW FORMAT DELIMITED
	FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/cbove/airports'
